### ISSUE TITLE
Install documentation not up to date

### ISSUE THREAD

**Issue by xfallme** [ConSol-Monitoring/nagflux#3]
Hello,

I was trying to install Nagflux from source into an existing Nagios installation and had the following problems:

- With Go 1.18 `go get` is now deprecated:
![image](https://github.com/user-attachments/assets/a7d9cd00-a997-4418-8478-242384c05f17)

- ... running `go install` instead gives the following error:
![image](https://github.com/user-attachments/assets/bd5be6f0-93b0-4d19-a82c-638dae39e794)

- Running with `@latest` results in this error:
![image](https://github.com/user-attachments/assets/0cd8d5c3-287e-434f-89a2-cff71d582103)
I am not really familiar with Go, but I think this is because your `go.mod` contains `module github.com/ConSol/nagflux`
instead of `ConSol-Monitoring`.

- So I ran `go install github.com/ConSol/nagflux@latest`:
![image](https://github.com/user-attachments/assets/7a1b0399-f69c-4d79-bfc0-57dad5c993c6)
But this also runs into an error.

Any help would be greatly appreciated!

**Comment by sni** [comment]
can you try again, we fixed the module path

**Comment by fvrflho** [comment]
Just tried to install, and got the following error:

>  go install github.com/ConSol-Monitoring/nagflux@latest
go: github.com/ConSol-Monitoring/nagflux@latest: version constraints conflict:
        github.com/ConSol-Monitoring/nagflux@v0.5.0: parsing go.mod:
        module declares its path as: github.com/ConSol/nagflux
                but was required as: github.com/ConSol-Monitoring/nagflux

If I clone the repository, I will find the following:

> grep -lir "/ConSol/" ./
> ./nagflux.service
> ./circle.yml
> ./coverage.sh

Best regards
/F

**Comment by sni** [comment]
alright, i created a new release with that url, so it should be fine now.

**Comment by sni** [comment]
i updated the installation docs, thanks for the report

**Comment by xfallme** [comment]
Sorry for the late response.
For both
`go install github.com/ConSol-Monitoring/nagflux/cmd/nagflux@latest` as well as `go install github.com/ConSol-Monitoring/nagflux/cmd/nagflux@v0.5.2` I now get:

> go: github.com/ConSol-Monitoring/nagflux/cmd/nagflux@v0.5.2 (in github.com/ConSol-Monitoring/nagflux@v0.5.2):
> 
> 	The go.mod file for the module providing named packages contains one or
> 	more replace directives. It must not contain directives that would cause
> 	it to be interpreted differently than if it were the main module.

According to https://github.com/golang/go/issues/44840#issuecomment-792789581 `replace` directives are not allowed in the go.mod

**Comment by sni** [comment]
I updated the installation once again to provide working steps. Actually that's how we build this project.
